#!/usr/bin/env bash

HOST="`hostname | sed -e 's/\([a-zA-Z0-9\-]*\).*/\1/'`"
USER="`whoami`"
HIM="$USER@$HOST"
WHEN="`date | awk '{
    if (NF==6) { print $1 " "  $2 " " $3 " "  $6 " at " $4 " " $5 }
    else       { print $1 " "  $2 " " $3 " " $7 " at " $4 " " $5 " " $6 }
}'`"

cat >version.c <<!END!
/**
 * @file version.c
 * @brief Generated version accessors (see version.h).
 *
 * Copyright (C) 2015-2026 unfacd works
 *
 * AUTO-GENERATED by version.c.sh — do not edit.
 *
 * Compiled: $WHEN
 * By:        $HIM
 */

#include <version.h>

#define STRINGISE_NX(A) #A
#define STRINGISE(A) STRINGISE_NX(A)

static const char *t_compiled  = "$WHEN";
static const char *u_compiled  = "$HIM";
static const char *ufsrv_version =
    STRINGISE(UFSRVRXLIB_MAJOR) "."
    STRINGISE(UFSRVRXLIB_MINOR) "."
    STRINGISE(UFSRVRXLIB_PATCH);

const char *UfsrvRxLibVersion(void)      { return ufsrv_version; }
const char *UfsrvRxLibVersionMajor(void) { return STRINGISE(UFSRVRXLIB_MAJOR); }
const char *UfsrvRxLibVersionMinor(void) { return STRINGISE(UFSRVRXLIB_MINOR); }
const char *UfsrvRxLibVersionPatch(void) { return STRINGISE(UFSRVRXLIB_PATCH); }
!END!
